---
title: "Clustering"
teaching: 0
exercises: 0
questions:
- "What does clustering mean?"
- "How can we cluster data with a model?"
- "How can we cluster data without a model?"
- "How can we check if clusters are robust?"
objectives:
- "Perform clustering with K-means and mixture models."
- "Assess clustering performance with silhouette score and bootstrapping."
keypoints:
- "KP1"
math: yes
---


```{r, include=FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("04-")
```

```{r}
## preamble
suppressPackageStartupMessages({
    library("scRNAseq")
    library("mixtools")
    library("irlba")
    library("scater")
    library("scuttle")
    library("scran")
    library("Rtsne")
    library("mclust")
    library("igraph")
    library("bluster")
})
set.seed(42)

if (!file.exists(here("data/scrnaseq.rds"))) {
    source(here("data/scrnaseq.R"))
}
norm <- readRDS(here("data/scrnaseq.rds"))


zd <- runPCA(zd, ncomponents = 15)
zd <- runTSNE(zd)



## k-means

## ideas: vary centers, low iter.max, low nstart
cluster <- kmeans(reducedDim(zd), centers = 7, iter.max = 1000, nstart = 100)
zd$kmeans <- as.character(cluster$cluster)

plotReducedDim(zd, "TSNE", colour_by = "kmeans")

## model-based
clust <- mclustBIC(reducedDim(zd), modelNames = "VVV")
opt_clust <- which.max(clust)
zd$mixture <- as.character(opt_clust)

plotReducedDim(zd, "TSNE", colour_by = "mixture")


## graph-based
g <- buildSNNGraph(zd, k=10, use.dimred = 'PCA')
clust <- igraph::cluster_walktrap(g)$membership
reducedDim(zd, "force") <- igraph::layout_with_fr(g)
colLabels(zd) <- factor(clust)
plotReducedDim(zd, colour_by="label", dimred="force")


# bluster::clusterRows - maybe?

## measures: silhouette, bootstrap
## approx silhouette? purity?
```


{% include links.md %}

